version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rightspot_db
      POSTGRES_USER: rightspot_user
      POSTGRES_PASSWORD: rightspot_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
